Edit puml and images
AY2223S2-CS2103-W16-2/tp pull request #269
Opened 2023-04-05 15:43 UTC by amoonguss1

This PR will update the images file with the correct notations for the DG. 
Updates the sequence diagram for CompanyCommand.
Partly resolves issue #159 and #260

2023-04-05 15:48 UTC, dsja612 requested changes
BetterModelClassDiagram needs a small fix and LGTM

2023-04-05 15:48 UTC, dsja612 commented on docs/images/ArchitectureSequenceDiagram.png
Good change. Lets check if the reduced image dimension might make the diagram hard to view in the DG.

2023-04-05 15:48 UTC, dsja612 commented on docs/images/ModelClassDiagram.png
Should be `company` instead of `address`

2023-04-05 15:59 UTC, amoonguss1 commented on docs/images/ModelClassDiagram.png
fixed as of the latest commit. Thanks for pointing it out!

2023-04-06 02:20 UTC, amoonguss1 reviewed
LGTM!

2023-04-06 02:20 UTC, dsja612 approved these changes

2023-04-06 02:20 UTC, merged

2023-04-06 02:21 UTC, RyanQiu1 commented on docs/diagrams/BetterModelClassDiagram.puml
LGTM, changing phone to contact makes it more suited.